; =============================================================================
; Xdebug 3 — конфігурація для розробки
; Значення можна перевизначити через змінні оточення
; =============================================================================

zend_extension=xdebug.so

xdebug.mode=develop,debug
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.idekey=VSCODE
xdebug.start_with_request=yes
xdebug.discover_client_host=0
xdebug.log=/tmp/xdebug.log
xdebug.log_level=7

xdebug.force_display_errors=1
xdebug.force_error_reporting=1
xdebug.show_error_trace=1
